language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
allow_failures:
  python:
    - "3.2"
    - "3.3"
    - "3.4"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors
  - python setup.py -q install
before_script:
  - "flake8 push_notifications"
script:
  - python tests/runtests.py
